name: AdvancedFindItem
version: ${version}
main: dev.hawu.plugins.finditem.MVFindItem
api-version: 1.15
description: ${description}
authors: [Haru, Pocketkid2]
softdepend: [QuickShop, Essentials, HikariLibrary]
commands:
  advancedfinditem:
    aliases: [afi]
    description: The base command for this plugin.
  finditem:
    aliases: [find]
    description: Command to find a shop willing to make transactions for the item.
permissions:
  afi.main:
    description: Allows access to the main command.
    default: op
  afi.find:
    description: Finds a shop willing to make transactions for the item.
    default: true
  afi.reload:
    description: Allows access to the reload sub-command.
    default: op
