name: Java CI with Maven
on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '*.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Build
        run: mvn clean package
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: './target/*.jar'
          name: "Artifacts"
